# needs: export UID
#
version: '3'
volumes:
    src:
        driver_opts:
            type: local
            device: ${PWD}/laravel
            o: bind

networks:
    my_network:
    proxy_ext_network:
        external: true

services:
    npm:
        build:
            context: ./
            dockerfile: ./npm/Dockerfile
        volumes:
            - src:/laravel
        user: "${UID}"
        environment:
            - TZ=Asia/Tokyo
    composer:
        build: 
            context: ./
            dockerfile: ./composer/Dockerfile
            args:
                - PHP_VERSION
        volumes: 
            - ./composer:/composer
            - ./laravel:/laravel
            - ./php.ini:/usr/local/etc/php/php.ini
        user: ${UID}
    # artisan:
    #     build: 
    #         context: ./
    #         dockerfile: ./artisan/Dockerfile
    #         args:
    #             - PHP_VERSION
    #     volumes:
    #         - src:/laravel
    #         - ./php.ini:/usr/local/etc/php/php.ini
    #     depends_on:
    #         - composer
    #     user: "${UID}"
    #     networks:
    #         - my_network
    #     environment:
    #         - TZ=Asia/Tokyo
    laravel:
        build:
            context: ./
            dockerfile: ./laravel/Dockerfile
            args:
                - PHP_VERSION
        volumes: 
            - src:/laravel
#            - ./laravel/php.ini:/usr/local/etc/php/php.ini
            - ./php.ini:/usr/local/etc/php/php.ini
        environment: 
            - TZ=Asia/Tokyo
            - XDG_CONFIG_HOME=/laravel
        depends_on:
            - npm
        networks:
            - my_network
        restart: always
        user: ${UID}
    web:
        build:
            context: ./
            dockerfile: web/Dockerfile
        depends_on:
            - laravel
        volumes:
            - src:/laravel
            - ./web/vhost.conf:/etc/nginx/conf.d/default.conf
            - ./web/log:/var/log/nginx
        environment:
            - TZ=Asia/Tokyo
        networks:
            - my_network
            - proxy_ext_network
        restart: always
    