version: '3'
services:
    web: 
        ports:
            - "${WEB_PORT}:80"
    artisan:
        depends_on: 
            - dev_mysql
    laravel:
        depends_on: 
            - dev_mysql
    dev_mysql:
        build:
            context: ./
            dockerfile: ./mysql/Dockerfile
        # user: "${UID}"
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
        ports:
            - "3306:3306"
        networks: 
            - my_network
        restart: always
