version: '3'
services:
    web: 
        ports:
            - "${WEB_PORT}:80"
    # artisan:
    #     depends_on: 
    #         - dev_mysql
    laravel:
        depends_on: 
            - dev_mysql
    phpunit:
        build:
            context: ./
            dockerfile: ./phpunit/Dockerfile
            args:
                - PHP_VERSION
        volumes:
            - src:/laravel
            - ./php.ini:/usr/local/etc/php/php.ini
            - ./phpunit/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        depends_on:
            - composer
            - dev_mysql
        user: "${UID}"
        networks:
            - my_network
        environment:
            - TZ=Asia/Tokyo
    dev_mysql:
        build:
            context: ./
            dockerfile: ./mysql/Dockerfile
        user: "${UID}"
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
        ports:
            - "${EXPOSE_PORT_PREFIX}3306:3306"
        networks: 
            - my_network
        restart: always
