name: Laravel

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        ports: 
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
#         volumes: 
#           - mysql/conf.d/:/etc/mysql/conf.d
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: tests 

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_DATABASE: tests

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      working-directory: laravel/
      run: php -r "copy('.env.actions', '.env');"
    - name: cache vendor
      id: cache
      uses: actions/cache@v1
      with:
        path: ./laravel/vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: laravel/
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      working-directory: laravel/
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 laravel/storage laravel/bootstrap/cache
    - name: migrate
      working-directory: laravel/
      run: php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      working-directory: laravel/
      run: vendor/bin/phpunit
